version: "3.7"
services:
  attend:
    image: ghcr.io/dryrain39/du-attend-v2-server:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
#    build: .
    ports:
     - "${SERVER_OPEN_PORT:-20003}:8000"
    volumes:
      - ./db/promotion:/app/promotion_db/
      - ./db/user:/app/user_db/
      - ./cache/user:/app/qr_cache/
      - ./cache/token:/app/token_cache/
      - ./config:/app/config/
