name: build-and-push

on:
  push:
    branches: [ main ]          # 기본 브랜치
    tags: [ 'v*' ]           # 릴리스 태그(v1.2.3 등)
  workflow_dispatch:          # 수동 실행

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # <owner>/<repo>

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (멀티플랫폼 에뮬레이션)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx (빌더 인스턴스)
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   # repo → Settings → Actions → “Read & write packages” 확인

      - name: Extract image metadata (태그·라벨 자동 생성)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # 브랜치·태그·SHA별 태그 구성
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long
          flavor: |
            latest=true

      - name: Build & Push (AMD64 + ARM64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
